version: "3.9"

services:
  am-i-isolated:
    image: ghcr.io/edera-dev/am-i-isolated:nightly
    stdin_open: true
    tty: true
    pid: "host"
    network_mode: "host"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    restart: "no"