name: release
on:
  release:
    types:
    - published
permissions:
  contents: read
jobs:
  oci-image:
    runs-on: ubuntu-latest
    name: Release OCI image build
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: harden runner
      uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
      with:
        egress-policy: audit
    - name: checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: recursive
    - name: install cosign
      uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0
    - name: setup docker buildx
      uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
    - name: login to ghcr
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ghcr.io
        username: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"
    - name: docker build and push ${{ matrix.component }}
      uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d # v6.12.0
      id: push
      with:
        file: ./Dockerfile
        platforms: linux/amd64,linux/aarch64
        tags: "ghcr.io/edera-dev/am-i-isolated:${{ github.event.release.tag_name }},ghcr.io/edera-dev/am-i-isolated:latest"
        push: true
    - name: cosign sign tag
      run: cosign sign --yes "${TAGS}@${DIGEST}"
      env:
        DIGEST: "${{ steps.push.outputs.digest }}"
        TAGS: "ghcr.io/edera-dev/am-i-isolated:${{ github.event.release.tag_name }}"
        COSIGN_EXPERIMENTAL: "true"
    - name: cosign sign latest
      run: cosign sign --yes "${TAGS}@${DIGEST}"
      env:
        DIGEST: "${{ steps.push.outputs.digest }}"
        TAGS: "ghcr.io/edera-dev/am-i-isolated:latest"
        COSIGN_EXPERIMENTAL: "true"
