name: release
on:
  release:
    types:
    - published
permissions:
  contents: read
jobs:
  oci-image:
    runs-on: ubuntu-latest
    name: Release OCI image build
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: harden runner
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit
    - name: checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: recursive
    - name: install cosign
      uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1
    - name: setup docker buildx
      uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0
    - name: login to ghcr
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ghcr.io
        username: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"
    - name: docker build and push ${{ matrix.component }}
      uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6.14.0
      id: push
      with:
        file: ./Dockerfile
        platforms: linux/amd64,linux/aarch64
        tags: "ghcr.io/edera-dev/am-i-isolated:${{ github.event.release.tag_name }},ghcr.io/edera-dev/am-i-isolated:latest"
        push: true
    - name: cosign sign tag
      run: cosign sign --yes "${TAGS}@${DIGEST}"
      env:
        DIGEST: "${{ steps.push.outputs.digest }}"
        TAGS: "ghcr.io/edera-dev/am-i-isolated:${{ github.event.release.tag_name }}"
        COSIGN_EXPERIMENTAL: "true"
    - name: cosign sign latest
      run: cosign sign --yes "${TAGS}@${DIGEST}"
      env:
        DIGEST: "${{ steps.push.outputs.digest }}"
        TAGS: "ghcr.io/edera-dev/am-i-isolated:latest"
        COSIGN_EXPERIMENTAL: "true"
