apiVersion: batch/v1
kind: Job
metadata:
  name: am-i-isolated
spec:
  template:
    metadata:
      name: am-i-isolated
    spec:
      restartPolicy: Never
      containers:
      - name: am-i-isolated
        image: ghcr.io/edera-dev/am-i-isolated:nightly
  backoffLimit: 0